### PR TITLE
refactor(chore): fix any types sonar code smells

### LINKED ISSUE #204: Fix All the sonar issues
**Describe the bug**
Fix overall all the sonar issues 
https://sonarcloud.io/summary/overall?id=sourcefuse_loopback4-authentication

### PR DESCRIPTION
**Pull request by sf-sahil-jassal**
fix sonar code smells related to unexpected any types

GH-204

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #204 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/strategy-adapter.ts [hunk 1]
```diff
@@ -37,8 +38,7 @@ export class StrategyAdapter<T> {
     return new Promise<T | void>((resolve, reject) => {
       // mix-in passport additions like req.logIn and req.logOut
       for (const key in passportRequestMixin) {
-        /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
-        (request as any)[key] = passportRequestMixin[key];
+        (request as AnyObject)[key] = passportRequestMixin[key];
```
Comment (yeshamavani) [inline src/strategy-adapter.ts:41]: why any object here

Comment (sf-sahil-jassal) [reply src/strategy-adapter.ts:41]: bcz we are adding more keys (logIn, login, logOut, logout, isAuthenticated, isUnauthenticated) in request of type Request (@loopback/repository). I am not completely sure, if any other keys were being added. I just console.log(key) in loop. That's why, I defined AnyObject
