### PR TITLE
fix(chore): export mandatory strategies from package 

### LINKED ISSUE #214: remove bearer and client password typeVersions export
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by sf-sahil-jassal**
remove bearer and client password passport strategies type declarations export
and export them from root

GH-214

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #214

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by yeshamavani — APPROVED** [review]

File: src/strategies/passport/index.ts [hunk 1]
```diff
@@ -1,3 +1,2 @@
-export * from './passport-otp';
```
Comment (yeshamavani) [inline src/strategies/passport/index.ts:1]: why remove this?

**Review by yeshamavani — APPROVED** [review]

File: src/strategies/passport/index.ts (hunk 1 above)
Comment (yeshamavani) [reply src/strategies/passport/index.ts:1]: since exported from package.json
